import React from 'react';
import JSZip from 'jszip';
import { ManuscriptAnalysis } from '../types';

interface ResultsDisplayProps {
  originalImageUrl: string;
  restoredImageUrl: string | null;
  analysis: ManuscriptAnalysis | null;
}

const ResultsDisplay: React.FC<ResultsDisplayProps> = ({ 
  originalImageUrl, 
  restoredImageUrl, 
  analysis 
}) => {

  const handleDownloadAll = async () => {
    const zip = new JSZip();

    // 1. Add Original Image
    if (originalImageUrl) {
      // Strip metadata prefix to get raw base64
      const originalData = originalImageUrl.split(',')[1];
      zip.file("original_manuscript.png", originalData, { base64: true });
    }

    // 2. Add Restored Image
    if (restoredImageUrl) {
      const restoredData = restoredImageUrl.split(',')[1];
      zip.file("restored_manuscript.png", restoredData, { base64: true });
    }

    // 3. Add Text Analysis
    if (analysis) {
      zip.file("transcription_tamil.txt", analysis.transcription);
      zip.file("translation_english.txt", analysis.translation);

      const combinedReport = `PALM-LEAF MANUSCRIPT ANALYSIS
=============================

[TRANSCRIPTION - MODERN TAMIL]
${analysis.transcription}

-----------------------------

[TRANSLATION - ENGLISH]
${analysis.translation}

=============================
Generated by PalmLeaf Restorer
`;
      zip.file("full_report.txt", combinedReport);
    }

    try {
      // Generate the zip file asynchronously
      const content = await zip.generateAsync({ type: "blob" });
      
      // Trigger download
      const url = window.URL.createObjectURL(content);
      const link = document.createElement('a');
      link.href = url;
      link.download = "manuscript_bundle.zip";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Failed to generate zip", error);
      alert("Could not generate download bundle.");
    }
  };

  const isDataReady = originalImageUrl || restoredImageUrl || analysis;

  return (
    <div className="w-full max-w-6xl mx-auto animate-fade-in space-y-6">
      
      {/* Action Bar */}
      {isDataReady && (
        <div className="flex justify-end">
          <button
            onClick={handleDownloadAll}
            className="flex items-center gap-2 px-5 py-2.5 bg-amber-600 hover:bg-amber-700 text-white font-medium rounded-lg shadow-sm transition-colors"
            title="Download original, restored image, and text analysis as a .zip file"
          >
            <span>📦</span>
            <span>Download All</span>
          </button>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        
        {/* Visuals Column */}
        <div className="space-y-8">
          {/* Original Image */}
          <div className="bg-white p-4 rounded-xl shadow-sm border border-stone-200">
            <div className="flex items-center gap-2 mb-3 border-b border-stone-100 pb-2">
              <span className="text-xl">🏚️</span>
              <h2 className="text-lg font-bold text-stone-800">Original Manuscript</h2>
            </div>
            <div className="relative aspect-video bg-stone-100 rounded-lg overflow-hidden flex items-center justify-center">
              <img 
                src={originalImageUrl} 
                alt="Original Manuscript" 
                className="object-contain w-full h-full"
              />
            </div>
          </div>

          {/* Restored Image */}
          <div className="bg-white p-4 rounded-xl shadow-sm border border-stone-200">
            <div className="flex items-center gap-2 mb-3 border-b border-stone-100 pb-2">
              <span className="text-xl">✨</span>
              <h2 className="text-lg font-bold text-stone-800">Digitally Restored</h2>
            </div>
            <div className="relative aspect-video bg-stone-100 rounded-lg overflow-hidden flex items-center justify-center">
              {restoredImageUrl ? (
                <img 
                  src={restoredImageUrl} 
                  alt="Restored Manuscript" 
                  className="object-contain w-full h-full"
                />
              ) : (
                <div className="text-stone-400 flex flex-col items-center">
                  <span className="text-3xl mb-2">⏳</span>
                  <span>Restoring...</span>
                </div>
              )}
            </div>
            {restoredImageUrl && (
              <div className="mt-2 text-right">
                <a 
                  href={restoredImageUrl} 
                  download="restored-manuscript.png" 
                  className="text-amber-700 text-sm hover:underline font-medium inline-flex items-center gap-1"
                >
                  Download Image ⬇️
                </a>
              </div>
            )}
          </div>
        </div>

        {/* Text Analysis Column */}
        <div className="space-y-8">
          
          {/* Transcription */}
          <div className="bg-white p-6 rounded-xl shadow-sm border border-stone-200 h-full flex flex-col">
            <div className="flex items-center gap-2 mb-4 border-b border-stone-100 pb-2">
              <span className="text-xl">✍️</span>
              <h2 className="text-lg font-bold text-stone-800">Modern Tamil Transcription</h2>
            </div>
            <div className="flex-grow bg-stone-50 p-4 rounded-lg border border-stone-100">
              {analysis ? (
                <p className="text-lg leading-relaxed text-stone-900 font-serif whitespace-pre-wrap">
                  {analysis.transcription}
                </p>
              ) : (
                <div className="h-24 flex items-center justify-center text-stone-400">
                  <span>Analyzing script...</span>
                </div>
              )}
            </div>
          </div>

          {/* Translation */}
          <div className="bg-white p-6 rounded-xl shadow-sm border border-stone-200 h-full flex flex-col">
            <div className="flex items-center gap-2 mb-4 border-b border-stone-100 pb-2">
              <span className="text-xl">🌍</span>
              <h2 className="text-lg font-bold text-stone-800">English Translation</h2>
            </div>
            <div className="flex-grow bg-stone-50 p-4 rounded-lg border border-stone-100">
              {analysis ? (
                <p className="text-lg leading-relaxed text-stone-800 whitespace-pre-wrap">
                  {analysis.translation}
                </p>
              ) : (
                <div className="h-24 flex items-center justify-center text-stone-400">
                  <span>Translating...</span>
                </div>
              )}
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};

export default ResultsDisplay;