import React, { useState } from 'react';
import JSZip from 'jszip';
import { ManuscriptAnalysis, KolamType } from '../types';
import { AnimatedBorder, AnimatedKolamMotif } from './AnimatedKolam';

interface ResultsDisplayProps {
  originalImageUrl: string;
  restoredImageUrl: string | null;
  analysis: ManuscriptAnalysis | null;
  onRetryRestoration: () => void;
  isRestoring: boolean;
  kolamType: KolamType;
}

// --- HELPER COMPONENTS ---

const CopyButton: React.FC<{ text: string }> = ({ text }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy', err);
    }
  };

  return (
    <button
      onClick={handleCopy}
      className="text-amber-700 hover:text-amber-500 hover:bg-amber-950/50 px-2 py-1 rounded text-xs sm:text-sm transition-colors flex items-center gap-1 border border-transparent hover:border-amber-900/30"
      title="Copy to clipboard"
    >
      {copied ? <span className="text-green-600 font-bold">✓</span> : 
         <span className="font-serif text-xs uppercase tracking-wider">Copy</span>
      }
    </button>
  );
};

const SafeImage: React.FC<{ src: string; alt: string; className?: string }> = ({ src, alt, className }) => {
  const [hasError, setHasError] = useState(false);

  if (hasError) {
    return (
      <div className={`flex flex-col items-center justify-center bg-[#2a1205] text-amber-800 p-8 ${className}`}>
        <span className="text-3xl mb-2">⚠️</span>
        <span className="text-xs text-center">Image failed to load</span>
      </div>
    );
  }

  return (
    <img
      src={src}
      alt={alt}
      className={`${className} bg-[#2a1205]`} 
      onError={() => setHasError(true)}
      loading="lazy"
    />
  );
};

const ResultsDisplay: React.FC<ResultsDisplayProps> = ({ 
  originalImageUrl, 
  restoredImageUrl, 
  analysis,
  onRetryRestoration,
  isRestoring,
  kolamType
}) => {

  const handleDownloadAll = async () => {
    const zip = new JSZip();
    // (Zip Logic remains same)
    if (originalImageUrl) {
      const originalData = originalImageUrl.split(',')[1];
      zip.file("original_manuscript.png", originalData, { base64: true });
    }
    if (restoredImageUrl) {
      const restoredData = restoredImageUrl.split(',')[1];
      zip.file("restored_manuscript.png", restoredData, { base64: true });
    }
    if (analysis) {
      zip.file("raw_ocr.txt", analysis.rawOCR);
      zip.file("transcription_tamil.txt", analysis.transcription);
      zip.file("translation_english.txt", analysis.translation);
      let sourceReport = "";
      if (analysis.sourceInfo) {
        sourceReport = `\n-----------------------------\n[SOURCE IDENTIFICATION]\nWork: ${analysis.sourceInfo.detectedSource}\nSection: ${analysis.sourceInfo.section}\nContext: ${analysis.sourceInfo.briefExplanation}\n`;
      }
      const combinedReport = `PALM-LEAF MANUSCRIPT ANALYSIS\n=============================\n\n[RAW OCR EXTRACTION]\n${analysis.rawOCR}\n\n-----------------------------\n\n[TRANSCRIPTION - MODERN TAMIL]\n${analysis.transcription}\n\n-----------------------------\n\n[TRANSLATION - ENGLISH]\n${analysis.translation}\n${sourceReport}\n=============================\nGenerated by PalmLeaf Restorer\n`;
      zip.file("full_report.txt", combinedReport);
    }

    try {
      const content = await zip.generateAsync({ type: "blob" });
      const url = window.URL.createObjectURL(content);
      const link = document.createElement('a');
      link.href = url;
      link.download = "manuscript_bundle.zip";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Failed to generate zip", error);
      alert("Could not generate download bundle.");
    }
  };

  const downloadTextFile = (filename: string, content: string) => {
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  const isDataReady = originalImageUrl || restoredImageUrl || analysis;

  const isSourceIdentified = analysis?.sourceInfo && 
    !analysis.sourceInfo.detectedSource.toLowerCase().includes('unidentified') && 
    !analysis.sourceInfo.detectedSource.toLowerCase().includes('general') &&
    !analysis.sourceInfo.detectedSource.toLowerCase().includes('unknown');

  return (
    <div className="w-full mx-auto animate-fade-in space-y-8 sm:space-y-10">
      
      {/* Action Bar */}
      {isDataReady && (
        <div className="flex justify-center sm:justify-end pb-2 relative z-10">
          <div className="relative group w-full sm:w-auto">
            <button
              onClick={handleDownloadAll}
              className="w-full sm:w-auto flex items-center justify-center gap-3 px-6 py-3 bg-amber-900 hover:bg-amber-800 text-amber-100 font-serif font-bold rounded shadow-md border-2 border-amber-700 transition-all hover:-translate-y-0.5 relative overflow-hidden"
            >
              <div className="absolute inset-0 bg-white/5 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
              <AnimatedKolamMotif size={24} seed={88} color="#fcd34d" type={kolamType} />
              <span className="tracking-wide">Download Archive</span>
            </button>
            
            {/* Custom Tooltip */}
            <div className="hidden sm:block absolute right-0 top-full mt-3 w-64 p-4 bg-[#1a0b05] text-amber-200/80 text-xs rounded shadow-2xl opacity-0 invisible group-hover:visible group-hover:opacity-100 transition-all duration-300 z-50 transform translate-y-[-5px] group-hover:translate-y-0 border border-amber-900">
              <div className="absolute -top-1.5 right-8 w-3 h-3 bg-[#1a0b05] border-l border-t border-amber-900 transform rotate-45"></div>
              <p className="font-bold mb-3 text-amber-500 border-b border-amber-900/50 pb-2 uppercase tracking-widest text-[10px]">Contents</p>
              <ul className="space-y-2 text-amber-200/60 font-serif">
                <li className="flex items-center gap-2"><span className="text-amber-600">▪</span> Original Image</li>
                <li className="flex items-center gap-2"><span className="text-amber-600">▪</span> Restored Image</li>
                <li className="flex items-center gap-2"><span className="text-amber-600">▪</span> Analysis Report</li>
              </ul>
            </div>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 sm:gap-8 items-start">
        
        {/* Left Column: Visuals */}
        <div className="space-y-6 sm:space-y-8">
          
          {/* Original Image Card */}
          <AnimatedBorder seed={101} type={kolamType}>
             <div className="bg-[#1a0b05] p-1 shadow-xl">
                 <div className="bg-[#2a1205] border border-amber-900/40 p-3">
                     <div className="flex items-center gap-2 mb-3 px-1">
                        <AnimatedKolamMotif size={20} seed={202} color="#92400e" type={kolamType} />
                        <h2 className="font-serif font-bold uppercase tracking-widest text-xs sm:text-sm text-amber-200/80">Original Manuscript</h2>
                     </div>
                     <div className="relative w-full bg-[#2a1205] overflow-hidden flex items-center justify-center shadow-inner min-h-[200px]">
                        <SafeImage 
                            src={originalImageUrl} 
                            alt="Original Manuscript" 
                            className="w-full h-auto object-contain block"
                        />
                     </div>
                     {/* Raw OCR Section */}
                     <div className="mt-4 bg-[#120402] border border-amber-900/30 p-3 shadow-inner">
                        <div className="flex items-center justify-between mb-2 border-b border-amber-900/20 pb-1">
                            <h3 className="text-[10px] font-bold text-amber-800 uppercase tracking-widest">Raw OCR Extraction</h3>
                            {analysis?.rawOCR && <CopyButton text={analysis.rawOCR} />}
                        </div>
                        <div className="max-h-32 overflow-y-auto custom-scrollbar">
                            <p className="text-xs text-amber-200/60 font-mono whitespace-pre-wrap leading-relaxed break-words">
                            {analysis?.rawOCR || "Waiting for analysis..."}
                            </p>
                        </div>
                    </div>
                 </div>
             </div>
          </AnimatedBorder>


          {/* Restored Image Card */}
          <AnimatedBorder seed={303} type={kolamType}>
             <div className="bg-[#1a0b05] p-1 shadow-xl">
                <div className="bg-[#2a1205] border border-amber-900/40 p-3">
                     <div className="flex items-center justify-between mb-3 px-1">
                         <div className="flex items-center gap-2">
                             <AnimatedKolamMotif size={20} seed={404} color="#f59e0b" type={kolamType} />
                             <h2 className="font-serif font-bold uppercase tracking-widest text-xs sm:text-sm text-amber-400">Digitally Restored</h2>
                         </div>
                         <div className="flex gap-2">
                             {restoredImageUrl && !isRestoring && (
                                <>
                                <button 
                                    onClick={onRetryRestoration}
                                    className="text-amber-700 hover:text-amber-500 p-1.5 rounded-full hover:bg-amber-950/50 transition-colors"
                                    title="Regenerate Variation"
                                >
                                    <span className="text-lg">↺</span>
                                </button>
                                <a 
                                    href={restoredImageUrl} 
                                    download="restored-manuscript.png" 
                                    className="text-amber-500 hover:text-amber-400 font-bold text-[10px] sm:text-xs uppercase tracking-wide flex items-center gap-1 border border-amber-900/50 px-2 py-1 rounded bg-amber-950/30 hover:bg-amber-900/50 transition-colors"
                                >
                                    ⬇ Save
                                </a>
                                </>
                            )}
                         </div>
                     </div>
                     
                     <div className="relative w-full bg-[#2a1205] overflow-hidden flex items-center justify-center shadow-inner min-h-[200px]">
                        {isRestoring ? (
                           <div className="flex flex-col items-center justify-center p-8 text-amber-500/60 absolute inset-0 bg-[#2a1205]/90 z-10 backdrop-blur-[1px]">
                            {/* Replaced rotate with drawing loop */}
                            <AnimatedKolamMotif size={64} seed={Date.now()} color="#d97706" className="mb-4" type={kolamType} loading={true} />
                            <span className="text-sm font-serif italic">Weaving pixels...</span>
                          </div>
                        ) : null}
                        
                        {restoredImageUrl ? (
                          <SafeImage 
                            src={restoredImageUrl} 
                            alt="Restored Manuscript" 
                            className={`w-full h-auto object-contain block transition-opacity duration-500 ${isRestoring ? 'opacity-20' : 'opacity-100'}`}
                          />
                        ) : (
                          <div className="flex flex-col items-center justify-center p-12 text-amber-900/50">
                            <div className="w-12 h-12 border-2 border-dashed border-amber-900/50 rounded-full mb-3"></div>
                            <span className="text-sm font-serif italic">Awaiting restoration...</span>
                          </div>
                        )}
                      </div>
                </div>
             </div>
          </AnimatedBorder>
        </div>

        {/* Right Column: Text Analysis */}
        <div className="space-y-6 sm:space-y-8">

           {/* Literary Source Card */}
           {analysis?.sourceInfo && (
            <AnimatedBorder seed={505} type={kolamType}>
              <div className="bg-[#1a0b05] p-1 shadow-xl">
                <div 
                    className={`rounded-sm overflow-hidden relative transition-all duration-500 group bg-[#1a0b05] border border-amber-900/40`}
                >
                    {/* Header Section */}
                    <div className={`px-4 sm:px-5 py-3 sm:py-4 border-b flex items-center gap-3 relative z-10
                    ${isSourceIdentified ? 'border-amber-900/60 bg-amber-900/40' : 'border-amber-900/30'}
                    `}>
                    <AnimatedKolamMotif size={24} seed={600} color={isSourceIdentified ? "#fbbf24" : "#78350f"} type={kolamType} />
                    <h2 className={`text-xs sm:text-sm font-serif font-extrabold uppercase tracking-widest
                        ${isSourceIdentified ? 'text-amber-400 drop-shadow-sm' : 'text-amber-800'}
                    `}>Source Identification</h2>
                    </div>
                    
                    {/* Content Section */}
                    <div className="p-4 sm:p-6 space-y-4 relative z-10">
                    <div className="flex flex-col gap-2">
                        <h3 className={`text-xl sm:text-2xl font-serif font-bold leading-snug tracking-wide drop-shadow-md
                        ${isSourceIdentified ? 'text-[#ffecb3]' : 'text-amber-900/80'}
                        `}>
                        {analysis.sourceInfo.detectedSource}
                        </h3>
                        {analysis.sourceInfo.section && (
                        <div className={`flex items-center gap-2 text-sm font-semibold uppercase tracking-wide
                            ${isSourceIdentified ? 'text-amber-500' : 'text-amber-900/60'}
                        `}>
                            <span className="w-6 sm:w-8 h-px bg-current opacity-70"></span>
                            {analysis.sourceInfo.section}
                        </div>
                        )}
                    </div>
                    <p className={`text-base sm:text-lg font-serif italic leading-relaxed border-l-4 pl-5 py-1
                        ${isSourceIdentified ? 'text-[#fff8e1] border-amber-600' : 'text-amber-900/60 border-amber-900/20'}
                    `}>
                        "{analysis.sourceInfo.briefExplanation}"
                    </p>
                    </div>
                </div>
              </div>
            </AnimatedBorder>
          )}
          
          {/* Transcription Card */}
          <AnimatedBorder seed={707} type={kolamType}>
             <div className="bg-[#1a0b05] p-1 shadow-xl">
                 <div className="bg-[#2a1205] border border-amber-900/40 p-3 h-[300px] flex flex-col">
                     <div className="flex items-center justify-between mb-3 px-1">
                         <div className="flex items-center gap-2">
                             <AnimatedKolamMotif size={20} seed={808} color="#d97706" type={kolamType} />
                             <h2 className="font-serif font-bold uppercase tracking-widest text-xs sm:text-sm text-amber-200/80">Modern Tamil Script</h2>
                         </div>
                         <div className="flex gap-2">
                             {analysis && (
                                <>
                                    <CopyButton text={analysis.transcription} />
                                    <button onClick={() => downloadTextFile("transcription.txt", analysis.transcription)} className="text-amber-700 hover:text-amber-500" title="Download">⬇</button>
                                </>
                             )}
                         </div>
                     </div>
                     <div className="flex-grow bg-[#120402] border border-amber-900/30 overflow-hidden relative">
                         <div className="absolute inset-0 overflow-y-auto p-4 sm:p-6 custom-scrollbar">
                             {analysis ? (
                                <p className="text-lg sm:text-xl leading-loose text-amber-100 font-serif whitespace-pre-wrap">
                                {analysis.transcription}
                                </p>
                            ) : (
                                <div className="flex flex-col items-center justify-center h-full text-amber-900/50 gap-3">
                                <span className="text-3xl opacity-50">...</span>
                                <span className="font-serif italic text-sm">Deciphering ancient script</span>
                                </div>
                            )}
                         </div>
                     </div>
                 </div>
             </div>
          </AnimatedBorder>


          {/* Translation Card */}
          <AnimatedBorder seed={909} type={kolamType}>
             <div className="bg-[#1a0b05] p-1 shadow-xl">
                 <div className="bg-[#2a1205] border border-amber-900/40 p-3 h-[300px] flex flex-col">
                     <div className="flex items-center justify-between mb-3 px-1">
                         <div className="flex items-center gap-2">
                             <AnimatedKolamMotif size={20} seed={1010} color="#d97706" type={kolamType} />
                             <h2 className="font-serif font-bold uppercase tracking-widest text-xs sm:text-sm text-amber-200/80">English Translation</h2>
                         </div>
                         <div className="flex gap-2">
                             {analysis && (
                                <>
                                    <CopyButton text={analysis.translation} />
                                    <button onClick={() => downloadTextFile("translation.txt", analysis.translation)} className="text-amber-700 hover:text-amber-500" title="Download">⬇</button>
                                </>
                             )}
                         </div>
                     </div>
                     <div className="flex-grow bg-[#120402] border border-amber-900/30 overflow-hidden relative">
                         <div className="absolute inset-0 overflow-y-auto p-4 sm:p-6 custom-scrollbar">
                             {analysis ? (
                                <p className="text-sm sm:text-base leading-7 text-amber-100/90 whitespace-pre-wrap font-serif">
                                {analysis.translation}
                                </p>
                            ) : (
                                <div className="flex flex-col items-center justify-center h-full text-amber-900/50 gap-3">
                                <span className="text-3xl opacity-50">...</span>
                                <span className="font-serif italic text-sm">Translating meaning</span>
                                </div>
                            )}
                         </div>
                     </div>
                 </div>
             </div>
          </AnimatedBorder>

        </div>
      </div>
    </div>
  );
};

export default ResultsDisplay;