import React, { useState } from 'react';
import JSZip from 'jszip';
import { ManuscriptAnalysis } from '../types';

interface ResultsDisplayProps {
  originalImageUrl: string;
  restoredImageUrl: string | null;
  analysis: ManuscriptAnalysis | null;
  onRetryRestoration: () => void;
  isRestoring: boolean;
}

const CopyButton: React.FC<{ text: string }> = ({ text }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy', err);
    }
  };

  return (
    <button
      onClick={handleCopy}
      className="text-stone-500 hover:text-amber-700 hover:bg-stone-100 px-2 py-1 rounded text-xs sm:text-sm transition-colors flex items-center gap-1 border border-transparent hover:border-stone-200"
      title="Copy to clipboard"
    >
      {copied ? <span>✅ Copied</span> : <span>📋 Copy</span>}
    </button>
  );
};

const SafeImage: React.FC<{ src: string; alt: string; className?: string }> = ({ src, alt, className }) => {
  const [hasError, setHasError] = useState(false);

  if (hasError) {
    return (
      <div className={`flex flex-col items-center justify-center bg-stone-100 text-stone-400 p-8 ${className}`}>
        <span className="text-3xl mb-2">⚠️</span>
        <span className="text-xs text-center">Image failed to load</span>
      </div>
    );
  }

  return (
    <img
      src={src}
      alt={alt}
      className={`${className} bg-stone-100`} // Force background to avoid transparency showing as black
      onError={() => setHasError(true)}
      loading="lazy"
    />
  );
};

const ResultsDisplay: React.FC<ResultsDisplayProps> = ({ 
  originalImageUrl, 
  restoredImageUrl, 
  analysis,
  onRetryRestoration,
  isRestoring
}) => {

  const handleDownloadAll = async () => {
    const zip = new JSZip();

    // 1. Add Original Image
    if (originalImageUrl) {
      const originalData = originalImageUrl.split(',')[1];
      zip.file("original_manuscript.png", originalData, { base64: true });
    }

    // 2. Add Restored Image
    if (restoredImageUrl) {
      const restoredData = restoredImageUrl.split(',')[1];
      zip.file("restored_manuscript.png", restoredData, { base64: true });
    }

    // 3. Add Text Analysis
    if (analysis) {
      zip.file("raw_ocr.txt", analysis.rawOCR);
      zip.file("transcription_tamil.txt", analysis.transcription);
      zip.file("translation_english.txt", analysis.translation);

      let sourceReport = "";
      // Check if sourceInfo exists (it might not on legacy records)
      if (analysis.sourceInfo) {
        sourceReport = `
-----------------------------

[SOURCE IDENTIFICATION]
Work: ${analysis.sourceInfo.detectedSource}
Section: ${analysis.sourceInfo.section}
Context: ${analysis.sourceInfo.briefExplanation}
`;
      }

      const combinedReport = `PALM-LEAF MANUSCRIPT ANALYSIS
=============================

[RAW OCR EXTRACTION]
${analysis.rawOCR}

-----------------------------

[TRANSCRIPTION - MODERN TAMIL]
${analysis.transcription}

-----------------------------

[TRANSLATION - ENGLISH]
${analysis.translation}
${sourceReport}
=============================
Generated by PalmLeaf Restorer
`;
      zip.file("full_report.txt", combinedReport);
    }

    try {
      const content = await zip.generateAsync({ type: "blob" });
      const url = window.URL.createObjectURL(content);
      const link = document.createElement('a');
      link.href = url;
      link.download = "manuscript_bundle.zip";
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Failed to generate zip", error);
      alert("Could not generate download bundle.");
    }
  };

  const downloadTextFile = (filename: string, content: string) => {
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  const isDataReady = originalImageUrl || restoredImageUrl || analysis;

  // Determine if source is identified (not "Unidentified" or "General text")
  const isSourceIdentified = analysis?.sourceInfo && 
    !analysis.sourceInfo.detectedSource.toLowerCase().includes('unidentified') && 
    !analysis.sourceInfo.detectedSource.toLowerCase().includes('general') &&
    !analysis.sourceInfo.detectedSource.toLowerCase().includes('unknown');

  return (
    <div className="w-full mx-auto animate-fade-in space-y-8">
      
      {/* Action Bar */}
      {isDataReady && (
        <div className="flex justify-end border-b border-stone-200 pb-4 relative z-10">
          <div className="relative group">
            <button
              onClick={handleDownloadAll}
              className="flex items-center gap-2 px-5 py-2.5 bg-amber-600 hover:bg-amber-700 text-white font-medium rounded-lg shadow-sm transition-transform active:scale-95 relative z-20"
            >
              <span className="text-xl">📦</span>
              <span>Download Archive</span>
            </button>
            
            {/* Custom Tooltip */}
            <div className="absolute right-0 top-full mt-3 w-64 p-3 bg-stone-800 text-stone-100 text-xs rounded-lg shadow-xl opacity-0 invisible group-hover:visible group-hover:opacity-100 transition-all duration-200 z-50 transform translate-y-[-5px] group-hover:translate-y-0 border border-stone-700">
              <div className="absolute -top-1.5 right-6 w-3 h-3 bg-stone-800 border-l border-t border-stone-700 transform rotate-45"></div>
              <p className="font-bold mb-2 text-amber-400 border-b border-stone-700 pb-1 uppercase tracking-wider text-[10px]">Included in Archive</p>
              <ul className="space-y-1.5 text-stone-300">
                <li className="flex items-center gap-2">
                  <span className="text-stone-500">📄</span> 
                  <span>Original Image <span className="text-stone-500 text-[10px] ml-1">(.png)</span></span>
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-stone-500">✨</span> 
                  <span>Restored Image <span className="text-stone-500 text-[10px] ml-1">(.png)</span></span>
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-stone-500">📝</span> 
                  <span>Analysis Report <span className="text-stone-500 text-[10px] ml-1">(.txt)</span></span>
                </li>
                {analysis?.sourceInfo && (
                  <li className="flex items-center gap-2">
                    <span className="text-stone-500">🔍</span> 
                    <span>Source Info <span className="text-stone-500 text-[10px] ml-1">(in report)</span></span>
                  </li>
                )}
              </ul>
            </div>
          </div>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
        
        {/* Left Column: Visuals */}
        <div className="space-y-6">
          {/* Original Image Card */}
          <div className="bg-white rounded-xl shadow-sm border border-stone-200 overflow-hidden">
            <div className="px-4 py-3 bg-stone-50 border-b border-stone-200 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="text-xl">🏚️</span>
                <h2 className="text-sm font-bold text-stone-700 uppercase tracking-wide">Original Manuscript</h2>
              </div>
            </div>
            
            <div className="p-4">
               <div className="relative w-full bg-stone-100 rounded-lg overflow-hidden border border-stone-200 flex items-center justify-center" style={{ minHeight: '200px' }}>
                <SafeImage 
                  src={originalImageUrl} 
                  alt="Original Manuscript" 
                  className="w-full h-auto object-contain block"
                />
              </div>
            </div>

            {/* Raw OCR Section (Collapsible/Scrollable) */}
            <div className="px-4 pb-4">
               <div className="bg-stone-50 rounded-lg border border-stone-200 p-3">
                  <div className="flex items-center justify-between mb-2">
                    <h3 className="text-xs font-bold text-stone-500 uppercase">Raw OCR Extraction</h3>
                    {analysis?.rawOCR && <CopyButton text={analysis.rawOCR} />}
                  </div>
                  <div className="max-h-32 overflow-y-auto custom-scrollbar">
                    <p className="text-xs text-stone-600 font-mono whitespace-pre-wrap">
                      {analysis?.rawOCR || "Waiting for analysis..."}
                    </p>
                  </div>
               </div>
            </div>
          </div>

          {/* Restored Image Card */}
          <div className="bg-white rounded-xl shadow-sm border border-stone-200 overflow-hidden">
            <div className="px-4 py-3 bg-stone-50 border-b border-stone-200 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="text-xl">✨</span>
                <h2 className="text-sm font-bold text-stone-700 uppercase tracking-wide">Digitally Restored</h2>
              </div>
              <div className="flex items-center gap-2">
                {restoredImageUrl && !isRestoring && (
                  <>
                  <button 
                    onClick={onRetryRestoration}
                    className="text-stone-500 hover:text-amber-700 hover:bg-stone-100 px-2 py-1 rounded text-xs sm:text-sm transition-colors flex items-center gap-1 border border-transparent hover:border-stone-200"
                    title="Run restoration again with variation"
                  >
                    <span>🔄</span> Regenerate
                  </button>
                  <a 
                    href={restoredImageUrl} 
                    download="restored-manuscript.png" 
                    className="text-amber-700 text-xs font-bold hover:underline flex items-center gap-1 ml-2"
                  >
                    ⬇️ SAVE
                  </a>
                  </>
                )}
              </div>
            </div>
            <div className="p-4">
              <div className="relative w-full bg-stone-100 rounded-lg overflow-hidden border border-stone-200 flex items-center justify-center" style={{ minHeight: '200px' }}>
                {isRestoring ? (
                   <div className="flex flex-col items-center justify-center p-8 text-stone-400 absolute inset-0 bg-white/80 z-10 backdrop-blur-sm">
                    <span className="text-3xl mb-2 animate-spin">🔄</span>
                    <span className="text-sm">Regenerating...</span>
                  </div>
                ) : null}
                
                {restoredImageUrl ? (
                  <SafeImage 
                    src={restoredImageUrl} 
                    alt="Restored Manuscript" 
                    className={`w-full h-auto object-contain block transition-opacity duration-300 ${isRestoring ? 'opacity-50' : 'opacity-100'}`}
                  />
                ) : (
                  <div className="flex flex-col items-center justify-center p-8 text-stone-400">
                    <span className="text-3xl mb-2 animate-pulse">⏳</span>
                    <span className="text-sm">Enhancing details...</span>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Right Column: Text Analysis */}
        <div className="space-y-6">

           {/* Literary Source Card - ALWAYS DISPLAYED if info exists */}
           {analysis?.sourceInfo && (
            <div 
              className={`rounded-xl shadow-sm border overflow-hidden relative transition-colors duration-300
                ${isSourceIdentified 
                  ? 'bg-amber-50 border-amber-200' 
                  : 'bg-stone-50 border-stone-200'
                }`}
            >
              <div className="absolute top-0 right-0 p-3 opacity-10 pointer-events-none">
                <span className="text-6xl">📖</span>
              </div>
              <div className={`px-4 py-3 border-b flex items-center gap-2
                 ${isSourceIdentified ? 'border-amber-100' : 'border-stone-200'}
              `}>
                <span className="text-xl">🔍</span>
                <h2 className={`text-sm font-bold uppercase tracking-wide
                  ${isSourceIdentified ? 'text-amber-800' : 'text-stone-600'}
                `}>Source Identification</h2>
              </div>
              <div className="p-4 space-y-2">
                <div className="flex flex-col sm:flex-row sm:items-baseline gap-1 sm:gap-2">
                  <h3 className={`text-lg font-bold leading-tight
                    ${isSourceIdentified ? 'text-amber-900' : 'text-stone-700'}
                  `}>
                    {analysis.sourceInfo.detectedSource}
                  </h3>
                  {analysis.sourceInfo.section && (
                    <span className={`text-sm font-medium
                       ${isSourceIdentified ? 'text-amber-700' : 'text-stone-500'}
                    `}>
                      • {analysis.sourceInfo.section}
                    </span>
                  )}
                </div>
                <p className={`text-sm leading-relaxed italic
                   ${isSourceIdentified ? 'text-amber-800/80' : 'text-stone-500'}
                `}>
                  "{analysis.sourceInfo.briefExplanation}"
                </p>
              </div>
            </div>
          )}
          
          {/* Transcription Card */}
          <div className="bg-white rounded-xl shadow-sm border border-stone-200 overflow-hidden flex flex-col h-full max-h-[600px]">
            <div className="px-4 py-3 bg-stone-50 border-b border-stone-200 flex items-center justify-between shrink-0">
              <div className="flex items-center gap-2">
                <span className="text-xl">✍️</span>
                <h2 className="text-sm font-bold text-stone-700 uppercase tracking-wide">Modern Tamil Transcription</h2>
              </div>
              {analysis && (
                <div className="flex items-center gap-2">
                  <CopyButton text={analysis.transcription} />
                  <button
                      onClick={() => downloadTextFile("transcription_tamil.txt", analysis.transcription)}
                      className="text-stone-500 hover:text-amber-700 hover:bg-stone-100 px-2 py-1 rounded text-xs transition-colors flex items-center gap-1"
                      title="Download text file"
                  >
                      ⬇️ TXT
                  </button>
                </div>
              )}
            </div>
            
            <div className="p-0 overflow-hidden flex-grow relative">
                <div className="absolute inset-0 overflow-y-auto p-4 custom-scrollbar">
                  {analysis ? (
                    <p className="text-lg leading-loose text-stone-900 font-serif whitespace-pre-wrap">
                      {analysis.transcription}
                    </p>
                  ) : (
                    <div className="flex flex-col items-center justify-center h-full text-stone-400 space-y-2">
                      <span className="text-2xl animate-bounce">...</span>
                      <span>Transcribing script</span>
                    </div>
                  )}
                </div>
            </div>
          </div>

          {/* Translation Card */}
          <div className="bg-white rounded-xl shadow-sm border border-stone-200 overflow-hidden flex flex-col h-full max-h-[600px]">
            <div className="px-4 py-3 bg-stone-50 border-b border-stone-200 flex items-center justify-between shrink-0">
              <div className="flex items-center gap-2">
                <span className="text-xl">🌍</span>
                <h2 className="text-sm font-bold text-stone-700 uppercase tracking-wide">English Translation</h2>
              </div>
              {analysis && (
                <div className="flex items-center gap-2">
                  <CopyButton text={analysis.translation} />
                  <button
                      onClick={() => downloadTextFile("translation_english.txt", analysis.translation)}
                      className="text-stone-500 hover:text-amber-700 hover:bg-stone-100 px-2 py-1 rounded text-xs transition-colors flex items-center gap-1"
                      title="Download text file"
                  >
                      ⬇️ TXT
                  </button>
                </div>
              )}
            </div>
            
             <div className="p-0 overflow-hidden flex-grow relative">
                <div className="absolute inset-0 overflow-y-auto p-4 custom-scrollbar">
                  {analysis ? (
                    <p className="text-base leading-relaxed text-stone-800 whitespace-pre-wrap font-sans">
                      {analysis.translation}
                    </p>
                  ) : (
                    <div className="flex flex-col items-center justify-center h-full text-stone-400 space-y-2">
                      <span className="text-2xl animate-bounce">...</span>
                      <span>Translating to English</span>
                    </div>
                  )}
                </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};

export default ResultsDisplay;